baseURL = "https://lucamailhol.com"
languageCode = "fr"
title = "Luca Mailhol"
sectionPagesMenu = "main"

[params]
  dateFormat = "Jan 2, 2006"

[permalinks]
  blog = "/:year/:month/:slug/"

[menu]
  [[menu.main]]
    identifier = "portfolio"
    name = "Portfolio"
    url = "/portfolio"
    weight = 1

  [[menu.main]]
    identifier = "cinema"
    name = "Cinéma"
    url = "/portfolio/cinema"
    parent = "portfolio"
    weight = 1

  [[menu.main]]
    identifier = "photo"
    name = "Photo"
    url = "/portfolio/photo"
    parent = "portfolio"
    weight = 2
  
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 2

 [[menu.main]]
    identifier = "a-propos"
    name = "À propos"
    url = "/a-propos"
    weight = 3


[taxonomies]
  tag = "tags"
  category = "categories"
