baseURL = "https://lucamailhol.com"
languageCode = "fr"
title = "Luca Mailhol"
sectionPagesMenu = "main"

[params]
  dateFormat = "Jan 2, 2006"

  [menu]
    [[menu.main]]
      name = "Accueil"
      url = "/"
      identifier = "accueil"
      weight = 1
    [[menu.main]]
      name = "Blog"
      url = "/blog/"
      identifier = "blog"
      weight = 2
    [[menu.main]]
      name = "À propos"
      url = "/a-propos/"
      identifier = "a-propos"
      weight = 3

[taxonomies]
  tag = "tags"
