baseURL = "https://lucamailhol.com"
languageCode = "fr"
title = "Luca Mailhol"
sectionPagesMenu = "main"

[params]
  dateFormat = "Jan 2, 2006"

  [menu]
    [[menu.main]]
      name = "Blog"
      url = "/blog/"
      identifier = "blog"
      weight = 1
    [[menu.main]]
      name = "Portfolio"
      url = "/portfolio/"
      identifier = "portfolio"
      weight = 2
    [[menu.main]]
      name = "Autre"
      url = "/autre/"
      identifier = "autre"
      weight = 3
    [[menu.main]]
      name = "Contact"
      url = "/contact/"
      identifier = "contact"
      weight = 4

[taxonomies]
  tag = "tags"
